In [1]:
import pandas as pd
import numpy as np

data=np.array([2000,18,18,3000,20,15,4000,18,20])
data=data.reshape(3,3)
print(data)
yeniDataFrame=pd.DataFrame(data,index=["Ömer","Faruk","Doğan"],columns=["Maas","Yas","Calisma Saati"])
print(yeniDataFrame)
ortalama=yeniDataFrame.Yas.mean()
yeniDataFrame["Yaş ortalaması"]=["Küçük" if i<ortalama else "Büyük" for i in yeniDataFrame.Yas]

veriler=yeniDataFrame
print(veriler)


[[2000   18   18]
 [3000   20   15]
 [4000   18   20]]
       Maas  Yas  Calisma Saati
Ömer   2000   18             18
Faruk  3000   20             15
Doğan  4000   18             20
       Maas  Yas  Calisma Saati Yaş ortalaması
Ömer   2000   18             18          Küçük
Faruk  3000   20             15          Büyük
Doğan  4000   18             20          Küçük


In [3]:
veriler.reset_index() #index ekledik.

index  Maas  Yas  Calisma Saati Yaş ortalaması
0   Ömer  2000   18             18          Küçük
1  Faruk  3000   20             15          Büyük
2  Doğan  4000   18             20          Küçük

In [4]:
yeni_index_list=["Omer","Far","Doğan"]
veriler["Yeni index"]=yeni_index_list

In [5]:
veriler

Maas  Yas  Calisma Saati Yaş ortalaması Yeni index
Ömer   2000   18             18          Küçük       Omer
Faruk  3000   20             15          Büyük        Far
Doğan  4000   18             20          Küçük      Doğan

In [7]:
veriler.set_index("Yeni index",inplace=True)

In [8]:
veriler

Maas  Yas  Calisma Saati Yaş ortalaması
Yeni index                                         
Omer        2000   18             18          Küçük
Far         3000   20             15          Büyük
Doğan       4000   18             20          Küçük